In [27]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error



In [28]:
data=fetch_california_housing()
# print(data)
df=pd.DataFrame(data.data,columns=data.feature_names)
# df.head()
df["Price"]=data.target

X=df.drop("Price",axis=1)
y=df["Price"]

linear=LinearRegression()
ridge=Ridge(alpha=1)
lasso=Lasso(alpha=0.01)
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

linear.fit(X_train,y_train)
ridge.fit(X_train,y_train)
lasso.fit(X_train,y_train)

linear.predict(X_test)
# ridge.predict(X_test)
# lasso.predict(X_test)





array([0.71912284, 1.76401657, 2.70965883, ..., 4.46877017, 1.18751119,
       2.00940251], shape=(4128,))

In [29]:
ridge.predict(X_test)


array([0.71923978, 1.76395141, 2.70909238, ..., 4.46864495, 1.18785499,
       2.00912494], shape=(4128,))

In [30]:
lasso.predict(X_test)

array([0.75752714, 1.74391678, 2.56439334, ..., 4.42843928, 1.28252423,
       1.93771376], shape=(4128,))

In [31]:
models={
    "Linear":linear,
    "Ridge":ridge,
    "Lasso":lasso
}

for name,model in models.items():
    pred=model.predict(X_test)

    print(name)
    print("MSE:",mean_squared_error(y_test,pred))
    print("MAE:",mean_absolute_error(y_test,pred))
    print("R2:",r2_score(y_test,pred))

Linear
MSE: 0.5558915986952442
MAE: 0.5332001304956555
R2: 0.575787706032451
Ridge
MSE: 0.5558034669932211
MAE: 0.5332039182571148
R2: 0.5758549611440126
Lasso
MSE: 0.5444491581246521
MAE: 0.5362504645663361
R2: 0.5845196673976367
